export default function Head() {
  return (
    <>
      <title>Candy Pass</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="/favicon.ico
      "
      />
    </>
  );
}
